export const NavList = [
  { key: 'dashboard', label: 'Dashboard' },
  { key: 'regions', label: 'Regions' },
  { key: 'lead', label: 'Lead' },
  { key: 'areas', label: 'Areas' },
  { key: 'support-agent', label: 'Support Agent' },
  { key: 'area-manager', label: 'Area Manager' },
  { key: 'bda', label: 'BDA' },
  { key: 'supervisor', label: 'Supervisor' },
  { key: 'trial', label: 'Trial' },
  { key: 'licenser', label: 'Licenser' },
  { key: 'region-manager', label: 'Region Manager' },
  { key: 'ticket', label: 'Ticket' },
  { key: 'prises', label: 'Prises' },
  { key: 'settings/users', label: ' Users' },
  { key: 'settings/users', label: 'Settings' },
  { key: 'settings/user-log', label: ' User Log' },
  { key: 'settings/target', label: ' Target' },
  { key: 'settings/business-card', label: 'Business Card' },
  { key: 'settings/worker-commission', label: ' Worker Commission' }
];
